import { Router } from 'express';
import { randomUUID } from 'node:crypto';
import { analyzeWithFallback, analyzeImageWithFallback } from '../ai/provider.js';
import { sanitizeText, analyzeLimiter, imageLimiter, validateType, isValidDataUrl } from '../middleware/security.js';
import { optionalAuth } from '../middleware/auth.js';
import { saveAnalysis } from '../db/db.js';
import { checkReputation, isReputationConfigured } from '../services/reputation.js';

export const analyzeRouter = Router();

function buildMeta({ type, inputSummary, mode, aiUsed, visualSource }) {
  return {
    type,
    inputSummary,
    mode,
    aiUsed,
    visualSource,
    sampleLabel: mode === 'demo' ? 'Demo Mode' : 'Live AI',
  };
}

/**
 * Extract URLs from text content for reputation checking.
 * Returns the first valid http/https URL found.
 */
function extractFirstUrl(text) {
  if (!text) return null;
  const match = text.match(/(https?:\/\/[^\s]+)/i);
  return match ? match[1].replace(/[.,;'"!)\]]+$/, '') : null;
}

/**
 * Build limitations array based on what checks were actually performed.
 */
function buildLimitations(type, hasReputation, aiUsed) {
  const limitations = [];
  if (!hasReputation) {
    limitations.push(
      'No external URL reputation provider was configured. Domain reputation could not be independently verified.',
    );
  }
  if (!aiUsed) {
    limitations.push(
      'AI explanation was not available. This report was generated by the deterministic heuristic engine.',
    );
  }
  if (type === 'url' || type === 'text') {
    limitations.push('URL analysis inspects link structure only — the URL was not opened or crawled.');
  }
  if (type === 'image') {
    limitations.push(
      aiUsed
        ? 'Image content was analyzed using the configured AI vision model.'
        : 'Image content was analyzed using user-supplied visible text only. Bundled OCR is not available in this build.',
    );
  }
  limitations.push('This assessment is based on pattern recognition — it is not a legal verdict about sender intent.');
  return limitations;
}

analyzeRouter.post('/analyze', analyzeLimiter, optionalAuth, async (req, res, next) => {
  try {
    const type = validateType(req.body?.type);
    const content = sanitizeText(req.body?.content);
    if (!content) {
      return res.status(400).json({ error: 'Please paste some text to analyze — the input was empty.' });
    }
    const { result, mode, aiUsed, aiError } = await analyzeWithFallback({ content, type });

    // Check reputation for any URLs embedded in the message text
    let reputationResult = null;
    const embeddedUrl = extractFirstUrl(content);
    if (embeddedUrl) {
      reputationResult = await checkReputation(embeddedUrl).catch((err) => {
        console.warn('[analyze] reputation check failed:', err.message);
        return null;
      });
    }

    const id = randomUUID();
    const payload = {
      id,
      ...result,
      type: type === 'demo' ? 'text' : type,
      inputSummary: content.slice(0, 90),
      mode,
      aiUsed,
      sampleLabel: mode === 'demo' ? 'Demo Mode' : 'Live AI',
      createdAt: new Date().toISOString(),
      reputationResult,
      limitations: buildLimitations(type === 'demo' ? 'text' : type, Boolean(reputationResult), aiUsed),
    };
    saveAnalysis(payload, req.user?.id);
    res.json({ ok: true, id, analysis: payload, mode, aiUsed, aiError: aiError || null });
  } catch (err) {
    next(err);
  }
});

analyzeRouter.post('/analyze/url', analyzeLimiter, optionalAuth, async (req, res, next) => {
  try {
    const content = sanitizeText(req.body?.url || req.body?.content);
    if (!content) {
      return res.status(400).json({ error: 'Please provide a URL to analyze.' });
    }
    const { result, mode, aiUsed, aiError } = await analyzeWithFallback({ content, type: 'url' });

    // For URL submissions, always run reputation check
    const reputationResult = await checkReputation(content).catch((err) => {
      console.warn('[analyze/url] reputation check failed:', err.message);
      return null;
    });

    const id = randomUUID();
    const payload = {
      id,
      ...result,
      type: 'url',
      inputSummary: content.slice(0, 90),
      mode,
      aiUsed,
      sampleLabel: mode === 'demo' ? 'Demo Mode' : 'Live AI',
      createdAt: new Date().toISOString(),
      reputationResult,
      limitations: buildLimitations('url', Boolean(reputationResult), aiUsed),
    };
    saveAnalysis(payload, req.user?.id);
    res.json({ ok: true, id, analysis: payload, mode, aiUsed, aiError: aiError || null });
  } catch (err) {
    next(err);
  }
});

analyzeRouter.post('/analyze/image', imageLimiter, optionalAuth, async (req, res, next) => {
  try {
    const dataUrl = req.body?.dataUrl;
    const visibleText = sanitizeText(req.body?.visibleText);
    if (!isValidDataUrl(dataUrl)) {
      return res.status(400).json({
        error: 'Please attach a valid PNG, JPG or WEBP image under 5 MB.',
      });
    }
    const { result, mode, aiUsed } = await analyzeImageWithFallback({ dataUrl, visibleText });

    // Check reputation of any URLs found in the extracted visual text
    let reputationResult = null;
    const extractedUrl = extractFirstUrl(visibleText) || extractFirstUrl(result?.visualScan?.extracted?.urls?.[0]);
    if (extractedUrl) {
      reputationResult = await checkReputation(extractedUrl).catch(() => null);
    }

    const id = randomUUID();
    const payload = {
      id,
      ...result,
      type: 'image',
      inputSummary: (visibleText || 'uploaded screenshot (illustrative scan)').slice(0, 90),
      mode,
      aiUsed,
      visualSource: result.visualScan ? 'scan' : undefined,
      sampleLabel: mode === 'demo' ? 'Demo Mode' : 'Live AI',
      createdAt: new Date().toISOString(),
      reputationResult,
      limitations: buildLimitations('image', Boolean(reputationResult), aiUsed),
    };
    saveAnalysis(payload, req.user?.id);
    res.json({ ok: true, id, analysis: payload, mode, aiUsed });
  } catch (err) {
    next(err);
  }
});

analyzeRouter.post('/generate-safe-reply', analyzeLimiter, async (req, res, next) => {
  try {
    const content = sanitizeText(req.body?.content);
    const category = sanitizeText(req.body?.category);
    const { result } = await analyzeWithFallback({
      content: content || category || 'a suspicious message',
      type: 'text',
    });
    res.json({ ok: true, safeReply: result.safeReply });
  } catch (err) {
    next(err);
  }
});